# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bowler_score.ui'
#
# Created: Mon Oct 27 11:03:03 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_bowler_score(object):
    def setupUi(self, bowler_score):
        bowler_score.setObjectName("bowler_score")
        bowler_score.resize(920, 101)
        self.verticalLayoutWidget = QtGui.QWidget(bowler_score)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 921, 101))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.line_59 = QtGui.QFrame(self.verticalLayoutWidget)
        self.line_59.setFrameShape(QtGui.QFrame.HLine)
        self.line_59.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_59.setObjectName("line_59")
        self.verticalLayout.addWidget(self.line_59)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.player_name = QtGui.QLabel(self.verticalLayoutWidget)
        self.player_name.setObjectName("player_name")
        self.horizontalLayout.addWidget(self.player_name)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.line_57 = QtGui.QFrame(self.verticalLayoutWidget)
        self.line_57.setFrameShape(QtGui.QFrame.VLine)
        self.line_57.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_57.setObjectName("line_57")
        self.horizontalLayout.addWidget(self.line_57)
        self.frame_1 = QtGui.QWidget(self.verticalLayoutWidget)
        self.frame_1.setMinimumSize(QtCore.QSize(60, 70))
        self.frame_1.setMaximumSize(QtCore.QSize(50, 70))
        self.frame_1.setObjectName("frame_1")
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.frame_1)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 30, 52, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.score_1 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(40)
        sizePolicy.setVerticalStretch(40)
        sizePolicy.setHeightForWidth(self.score_1.sizePolicy().hasHeightForWidth())
        self.score_1.setSizePolicy(sizePolicy)
        self.score_1.setMinimumSize(QtCore.QSize(40, 40))
        self.score_1.setMaximumSize(QtCore.QSize(16777215, 40))
        self.score_1.setText("")
        self.score_1.setAlignment(QtCore.Qt.AlignCenter)
        self.score_1.setObjectName("score_1")
        self.horizontalLayout_5.addWidget(self.score_1)
        self.horizontalLayoutWidget_3 = QtGui.QWidget(self.frame_1)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 57, 32))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.throw_1 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.throw_1.setMinimumSize(QtCore.QSize(20, 30))
        self.throw_1.setMaximumSize(QtCore.QSize(20, 30))
        self.throw_1.setText("")
        self.throw_1.setAlignment(QtCore.Qt.AlignCenter)
        self.throw_1.setObjectName("throw_1")
        self.horizontalLayout_6.addWidget(self.throw_1)
        self.line_21 = QtGui.QFrame(self.horizontalLayoutWidget_3)
        self.line_21.setFrameShape(QtGui.QFrame.VLine)
        self.line_21.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_21.setObjectName("line_21")
        self.horizontalLayout_6.addWidget(self.line_21)
        self.throw_2 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.throw_2.setMinimumSize(QtCore.QSize(20, 30))
        self.throw_2.setMaximumSize(QtCore.QSize(20, 30))
        self.throw_2.setText("")
        self.throw_2.setAlignment(QtCore.Qt.AlignCenter)
        self.throw_2.setObjectName("throw_2")
        self.horizontalLayout_6.addWidget(self.throw_2)
        self.horizontalLayout.addWidget(self.frame_1)
        self.line_48 = QtGui.QFrame(self.verticalLayoutWidget)
        self.line_48.setFrameShape(QtGui.QFrame.VLine)
        self.line_48.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_48.setObjectName("line_48")
        self.horizontalLayout.addWidget(self.line_48)
        self.frame_2 = QtGui.QWidget(self.verticalLayoutWidget)
        self.frame_2.setMinimumSize(QtCore.QSize(60, 70))
        self.frame_2.setMaximumSize(QtCore.QSize(50, 70))
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayoutWidget_72 = QtGui.QWidget(self.frame_2)
        self.horizontalLayoutWidget_72.setGeometry(QtCore.QRect(0, 30, 51, 42))
        self.horizontalLayoutWidget_72.setObjectName("horizontalLayoutWidget_72")
        self.horizontalLayout_39 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_72)
        self.horizontalLayout_39.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.score_2 = QtGui.QLabel(self.horizontalLayoutWidget_72)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(40)
        sizePolicy.setVerticalStretch(40)
        sizePolicy.setHeightForWidth(self.score_2.sizePolicy().hasHeightForWidth())
        self.score_2.setSizePolicy(sizePolicy)
        self.score_2.setMinimumSize(QtCore.QSize(40, 40))
        self.score_2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.score_2.setText("")
        self.score_2.setAlignment(QtCore.Qt.AlignCenter)
        self.score_2.setObjectName("score_2")
        self.horizontalLayout_39.addWidget(self.score_2)
        self.horizontalLayoutWidget_73 = QtGui.QWidget(self.frame_2)
        self.horizontalLayoutWidget_73.setGeometry(QtCore.QRect(0, 0, 57, 32))
        self.horizontalLayoutWidget_73.setObjectName("horizontalLayoutWidget_73")
        self.horizontalLayout_40 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_73)
        self.horizontalLayout_40.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.throw_3 = QtGui.QLabel(self.horizontalLayoutWidget_73)
        self.throw_3.setMinimumSize(QtCore.QSize(20, 30))
        self.throw_3.setMaximumSize(QtCore.QSize(20, 30))
        self.throw_3.setText("")
        self.throw_3.setAlignment(QtCore.Qt.AlignCenter)
        self.throw_3.setObjectName("throw_3")
        self.horizontalLayout_40.addWidget(self.throw_3)
        self.line_38 = QtGui.QFrame(self.horizontalLayoutWidget_73)
        self.line_38.setFrameShape(QtGui.QFrame.VLine)
        self.line_38.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_38.setObjectName("line_38")
        self.horizontalLayout_40.addWidget(self.line_38)
        self.throw_4 = QtGui.QLabel(self.horizontalLayoutWidget_73)
        self.throw_4.setMinimumSize(QtCore.QSize(20, 30))
        self.throw_4.setMaximumSize(QtCore.QSize(20, 30))
        self.throw_4.setText("")
        self.throw_4.setAlignment(QtCore.Qt.AlignCenter)
        self.throw_4.setObjectName("throw_4")
        self.horizontalLayout_40.addWidget(self.throw_4)
        self.horizontalLayout.addWidget(self.frame_2)
        self.line_49 = QtGui.QFrame(self.verticalLayoutWidget)
        self.line_49.setFrameShape(QtGui.QFrame.VLine)
        self.line_49.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_49.setObjectName("line_49")
        self.horizontalLayout.addWidget(self.line_49)
        self.frame_3 = QtGui.QWidget(self.verticalLayoutWidget)
        self.frame_3.setMinimumSize(QtCore.QSize(60, 70))
        self.frame_3.setMaximumSize(QtCore.QSize(50, 70))
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayoutWidget_74 = QtGui.QWidget(self.frame_3)
        self.horizontalLayoutWidget_74.setGeometry(QtCore.QRect(0, 30, 51, 42))
        self.horizontalLayoutWidget_74.setObjectName("horizontalLayoutWidget_74")
        self.horizontalLayout_41 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_74)
        self.horizontalLayout_41.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.score_3 = QtGui.QLabel(self.horizontalLayoutWidget_74)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(40)
        sizePolicy.setVerticalStretch(40)
        sizePolicy.setHeightForWidth(self.score_3.sizePolicy().hasHeightForWidth())
        self.score_3.setSizePolicy(sizePolicy)
        self.score_3.setMinimumSize(QtCore.QSize(40, 40))
        self.score_3.setText("")
        self.score_3.setAlignment(QtCore.Qt.AlignCenter)
        self.score_3.setObjectName("score_3")
        self.horizontalLayout_41.addWidget(self.score_3)
        self.horizontalLayoutWidget_75 = QtGui.QWidget(self.frame_3)
        self.horizontalLayoutWidget_75.setGeometry(QtCore.QRect(0, 0, 57, 32))
        self.horizontalLayoutWidget_75.setObjectName("horizontalLayoutWidget_75")
        self.horizontalLayout_42 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_75)
        self.horizontalLayout_42.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.throw_5 = QtGui.QLabel(self.horizontalLayoutWidget_75)
        self.throw_5.setMinimumSize(QtCore.QSize(20, 30))
        self.throw_5.setMaximumSize(QtCore.QSize(20, 30))
        self.throw_5.setText("")
        self.throw_5.setAlignment(QtCore.Qt.AlignCenter)
        self.throw_5.setObjectName("throw_5")
        self.horizontalLayout_42.addWidget(self.throw_5)
        self.line_39 = QtGui.QFrame(self.horizontalLayoutWidget_75)
        self.line_39.setFrameShape(QtGui.QFrame.VLine)
        self.line_39.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_39.setObjectName("line_39")
        self.horizontalLayout_42.addWidget(self.line_39)
        self.throw_6 = QtGui.QLabel(self.horizontalLayoutWidget_75)
        self.throw_6.setMinimumSize(QtCore.QSize(20, 30))
        self.throw_6.setMaximumSize(QtCore.QSize(20, 30))
        self.throw_6.setText("")
        self.throw_6.setAlignment(QtCore.Qt.AlignCenter)
        self.throw_6.setObjectName("throw_6")
        self.horizontalLayout_42.addWidget(self.throw_6)
        self.horizontalLayout.addWidget(self.frame_3)
        self.line_50 = QtGui.QFrame(self.verticalLayoutWidget)
        self.line_50.setFrameShape(QtGui.QFrame.VLine)
        self.line_50.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_50.setObjectName("line_50")
        self.horizontalLayout.addWidget(self.line_50)
        self.frame_4 = QtGui.QWidget(self.verticalLayoutWidget)
        self.frame_4.setMinimumSize(QtCore.QSize(60, 70))
        self.frame_4.setMaximumSize(QtCore.QSize(50, 70))
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayoutWidget_76 = QtGui.QWidget(self.frame_4)
        self.horizontalLayoutWidget_76.setGeometry(QtCore.QRect(0, 30, 51, 42))
        self.horizontalLayoutWidget_76.setObjectName("horizontalLayoutWidget_76")
        self.horizontalLayout_43 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_76)
        self.horizontalLayout_43.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.score_4 = QtGui.QLabel(self.horizontalLayoutWidget_76)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(40)
        sizePolicy.setVerticalStretch(40)
        sizePolicy.setHeightForWidth(self.score_4.sizePolicy().hasHeightForWidth())
        self.score_4.setSizePolicy(sizePolicy)
        self.score_4.setMinimumSize(QtCore.QSize(40, 40))
        self.score_4.setText("")
        self.score_4.setAlignment(QtCore.Qt.AlignCenter)
        self.score_4.setObjectName("score_4")
        self.horizontalLayout_43.addWidget(self.score_4)
        self.horizontalLayoutWidget_77 = QtGui.QWidget(self.frame_4)
        self.horizontalLayoutWidget_77.setGeometry(QtCore.QRect(0, 0, 57, 32))
        self.horizontalLayoutWidget_77.setObjectName("horizontalLayoutWidget_77")
        self.horizontalLayout_44 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_77)
        self.horizontalLayout_44.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.throw_7 = QtGui.QLabel(self.horizontalLayoutWidget_77)
        self.throw_7.setMinimumSize(QtCore.QSize(20, 30))
        self.throw_7.setMaximumSize(QtCore.QSize(20, 30))
        self.throw_7.setText("")
        self.throw_7.setAlignment(QtCore.Qt.AlignCenter)
        self.throw_7.setObjectName("throw_7")
        self.horizontalLayout_44.addWidget(self.throw_7)
        self.line_40 = QtGui.QFrame(self.horizontalLayoutWidget_77)
        self.line_40.setFrameShape(QtGui.QFrame.VLine)
        self.line_40.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_40.setObjectName("line_40")
        self.horizontalLayout_44.addWidget(self.line_40)
        self.throw_8 = QtGui.QLabel(self.horizontalLayoutWidget_77)
        self.throw_8.setMinimumSize(QtCore.QSize(20, 30))
        self.throw_8.setMaximumSize(QtCore.QSize(20, 30))
        self.throw_8.setText("")
        self.throw_8.setAlignment(QtCore.Qt.AlignCenter)
        self.throw_8.setObjectName("throw_8")
        self.horizontalLayout_44.addWidget(self.throw_8)
        self.horizontalLayout.addWidget(self.frame_4)
        self.line_51 = QtGui.QFrame(self.verticalLayoutWidget)
        self.line_51.setFrameShape(QtGui.QFrame.VLine)
        self.line_51.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_51.setObjectName("line_51")
        self.horizontalLayout.addWidget(self.line_51)
        self.frame_5 = QtGui.QWidget(self.verticalLayoutWidget)
        self.frame_5.setMinimumSize(QtCore.QSize(60, 70))
        self.frame_5.setMaximumSize(QtCore.QSize(50, 70))
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayoutWidget_78 = QtGui.QWidget(self.frame_5)
        self.horizontalLayoutWidget_78.setGeometry(QtCore.QRect(0, 30, 51, 42))
        self.horizontalLayoutWidget_78.setObjectName("horizontalLayoutWidget_78")
        self.horizontalLayout_45 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_78)
        self.horizontalLayout_45.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_45.setObjectName("horizontalLayout_45")
        self.score_5 = QtGui.QLabel(self.horizontalLayoutWidget_78)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(40)
        sizePolicy.setVerticalStretch(40)
        sizePolicy.setHeightForWidth(self.score_5.sizePolicy().hasHeightForWidth())
        self.score_5.setSizePolicy(sizePolicy)
        self.score_5.setMinimumSize(QtCore.QSize(40, 40))
        self.score_5.setText("")
        self.score_5.setAlignment(QtCore.Qt.AlignCenter)
        self.score_5.setObjectName("score_5")
        self.horizontalLayout_45.addWidget(self.score_5)
        self.horizontalLayoutWidget_79 = QtGui.QWidget(self.frame_5)
        self.horizontalLayoutWidget_79.setGeometry(QtCore.QRect(0, 0, 57, 32))
        self.horizontalLayoutWidget_79.setObjectName("horizontalLayoutWidget_79")
        self.horizontalLayout_46 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_79)
        self.horizontalLayout_46.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_46.setObjectName("horizontalLayout_46")
        self.throw_9 = QtGui.QLabel(self.horizontalLayoutWidget_79)
        self.throw_9.setMinimumSize(QtCore.QSize(20, 30))
        self.throw_9.setMaximumSize(QtCore.QSize(20, 30))
        self.throw_9.setText("")
        self.throw_9.setAlignment(QtCore.Qt.AlignCenter)
        self.throw_9.setObjectName("throw_9")
        self.horizontalLayout_46.addWidget(self.throw_9)
        self.line_41 = QtGui.QFrame(self.horizontalLayoutWidget_79)
        self.line_41.setFrameShape(QtGui.QFrame.VLine)
        self.line_41.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_41.setObjectName("line_41")
        self.horizontalLayout_46.addWidget(self.line_41)
        self.throw_10 = QtGui.QLabel(self.horizontalLayoutWidget_79)
        self.throw_10.setMinimumSize(QtCore.QSize(20, 30))
        self.throw_10.setMaximumSize(QtCore.QSize(20, 30))
        self.throw_10.setText("")
        self.throw_10.setAlignment(QtCore.Qt.AlignCenter)
        self.throw_10.setObjectName("throw_10")
        self.horizontalLayout_46.addWidget(self.throw_10)
        self.horizontalLayout.addWidget(self.frame_5)
        self.line_52 = QtGui.QFrame(self.verticalLayoutWidget)
        self.line_52.setFrameShape(QtGui.QFrame.VLine)
        self.line_52.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_52.setObjectName("line_52")
        self.horizontalLayout.addWidget(self.line_52)
        self.frame_6 = QtGui.QWidget(self.verticalLayoutWidget)
        self.frame_6.setMinimumSize(QtCore.QSize(60, 70))
        self.frame_6.setMaximumSize(QtCore.QSize(50, 70))
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayoutWidget_80 = QtGui.QWidget(self.frame_6)
        self.horizontalLayoutWidget_80.setGeometry(QtCore.QRect(0, 30, 51, 42))
        self.horizontalLayoutWidget_80.setObjectName("horizontalLayoutWidget_80")
        self.horizontalLayout_47 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_80)
        self.horizontalLayout_47.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_47.setObjectName("horizontalLayout_47")
        self.score_6 = QtGui.QLabel(self.horizontalLayoutWidget_80)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(40)
        sizePolicy.setVerticalStretch(40)
        sizePolicy.setHeightForWidth(self.score_6.sizePolicy().hasHeightForWidth())
        self.score_6.setSizePolicy(sizePolicy)
        self.score_6.setMinimumSize(QtCore.QSize(40, 40))
        self.score_6.setText("")
        self.score_6.setAlignment(QtCore.Qt.AlignCenter)
        self.score_6.setObjectName("score_6")
        self.horizontalLayout_47.addWidget(self.score_6)
        self.horizontalLayoutWidget_81 = QtGui.QWidget(self.frame_6)
        self.horizontalLayoutWidget_81.setGeometry(QtCore.QRect(0, 0, 57, 32))
        self.horizontalLayoutWidget_81.setObjectName("horizontalLayoutWidget_81")
        self.horizontalLayout_48 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_81)
        self.horizontalLayout_48.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_48.setObjectName("horizontalLayout_48")
        self.throw_11 = QtGui.QLabel(self.horizontalLayoutWidget_81)
        self.throw_11.setMinimumSize(QtCore.QSize(20, 30))
        self.throw_11.setMaximumSize(QtCore.QSize(20, 30))
        self.throw_11.setText("")
        self.throw_11.setAlignment(QtCore.Qt.AlignCenter)
        self.throw_11.setObjectName("throw_11")
        self.horizontalLayout_48.addWidget(self.throw_11)
        self.line_42 = QtGui.QFrame(self.horizontalLayoutWidget_81)
        self.line_42.setFrameShape(QtGui.QFrame.VLine)
        self.line_42.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_42.setObjectName("line_42")
        self.horizontalLayout_48.addWidget(self.line_42)
        self.throw_12 = QtGui.QLabel(self.horizontalLayoutWidget_81)
        self.throw_12.setMinimumSize(QtCore.QSize(20, 30))
        self.throw_12.setMaximumSize(QtCore.QSize(20, 30))
        self.throw_12.setText("")
        self.throw_12.setAlignment(QtCore.Qt.AlignCenter)
        self.throw_12.setObjectName("throw_12")
        self.horizontalLayout_48.addWidget(self.throw_12)
        self.horizontalLayout.addWidget(self.frame_6)
        self.line_53 = QtGui.QFrame(self.verticalLayoutWidget)
        self.line_53.setFrameShape(QtGui.QFrame.VLine)
        self.line_53.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_53.setObjectName("line_53")
        self.horizontalLayout.addWidget(self.line_53)
        self.frame_7 = QtGui.QWidget(self.verticalLayoutWidget)
        self.frame_7.setMinimumSize(QtCore.QSize(60, 70))
        self.frame_7.setMaximumSize(QtCore.QSize(50, 70))
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayoutWidget_82 = QtGui.QWidget(self.frame_7)
        self.horizontalLayoutWidget_82.setGeometry(QtCore.QRect(0, 30, 51, 42))
        self.horizontalLayoutWidget_82.setObjectName("horizontalLayoutWidget_82")
        self.horizontalLayout_49 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_82)
        self.horizontalLayout_49.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_49.setObjectName("horizontalLayout_49")
        self.score_7 = QtGui.QLabel(self.horizontalLayoutWidget_82)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(40)
        sizePolicy.setVerticalStretch(40)
        sizePolicy.setHeightForWidth(self.score_7.sizePolicy().hasHeightForWidth())
        self.score_7.setSizePolicy(sizePolicy)
        self.score_7.setMinimumSize(QtCore.QSize(40, 40))
        self.score_7.setText("")
        self.score_7.setAlignment(QtCore.Qt.AlignCenter)
        self.score_7.setObjectName("score_7")
        self.horizontalLayout_49.addWidget(self.score_7)
        self.horizontalLayoutWidget_83 = QtGui.QWidget(self.frame_7)
        self.horizontalLayoutWidget_83.setGeometry(QtCore.QRect(0, 0, 57, 32))
        self.horizontalLayoutWidget_83.setObjectName("horizontalLayoutWidget_83")
        self.horizontalLayout_50 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_83)
        self.horizontalLayout_50.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_50.setObjectName("horizontalLayout_50")
        self.throw_13 = QtGui.QLabel(self.horizontalLayoutWidget_83)
        self.throw_13.setMinimumSize(QtCore.QSize(20, 30))
        self.throw_13.setMaximumSize(QtCore.QSize(20, 30))
        self.throw_13.setText("")
        self.throw_13.setAlignment(QtCore.Qt.AlignCenter)
        self.throw_13.setObjectName("throw_13")
        self.horizontalLayout_50.addWidget(self.throw_13)
        self.line_43 = QtGui.QFrame(self.horizontalLayoutWidget_83)
        self.line_43.setFrameShape(QtGui.QFrame.VLine)
        self.line_43.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_43.setObjectName("line_43")
        self.horizontalLayout_50.addWidget(self.line_43)
        self.throw_14 = QtGui.QLabel(self.horizontalLayoutWidget_83)
        self.throw_14.setMinimumSize(QtCore.QSize(20, 30))
        self.throw_14.setMaximumSize(QtCore.QSize(20, 30))
        self.throw_14.setText("")
        self.throw_14.setAlignment(QtCore.Qt.AlignCenter)
        self.throw_14.setObjectName("throw_14")
        self.horizontalLayout_50.addWidget(self.throw_14)
        self.horizontalLayout.addWidget(self.frame_7)
        self.line_54 = QtGui.QFrame(self.verticalLayoutWidget)
        self.line_54.setFrameShape(QtGui.QFrame.VLine)
        self.line_54.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_54.setObjectName("line_54")
        self.horizontalLayout.addWidget(self.line_54)
        self.frame_8 = QtGui.QWidget(self.verticalLayoutWidget)
        self.frame_8.setMinimumSize(QtCore.QSize(60, 70))
        self.frame_8.setMaximumSize(QtCore.QSize(50, 70))
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayoutWidget_84 = QtGui.QWidget(self.frame_8)
        self.horizontalLayoutWidget_84.setGeometry(QtCore.QRect(0, 30, 51, 42))
        self.horizontalLayoutWidget_84.setObjectName("horizontalLayoutWidget_84")
        self.horizontalLayout_51 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_84)
        self.horizontalLayout_51.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_51.setObjectName("horizontalLayout_51")
        self.score_8 = QtGui.QLabel(self.horizontalLayoutWidget_84)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(40)
        sizePolicy.setVerticalStretch(40)
        sizePolicy.setHeightForWidth(self.score_8.sizePolicy().hasHeightForWidth())
        self.score_8.setSizePolicy(sizePolicy)
        self.score_8.setMinimumSize(QtCore.QSize(40, 40))
        self.score_8.setText("")
        self.score_8.setAlignment(QtCore.Qt.AlignCenter)
        self.score_8.setObjectName("score_8")
        self.horizontalLayout_51.addWidget(self.score_8)
        self.horizontalLayoutWidget_85 = QtGui.QWidget(self.frame_8)
        self.horizontalLayoutWidget_85.setGeometry(QtCore.QRect(0, 0, 57, 32))
        self.horizontalLayoutWidget_85.setObjectName("horizontalLayoutWidget_85")
        self.horizontalLayout_52 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_85)
        self.horizontalLayout_52.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_52.setObjectName("horizontalLayout_52")
        self.throw_15 = QtGui.QLabel(self.horizontalLayoutWidget_85)
        self.throw_15.setMinimumSize(QtCore.QSize(20, 30))
        self.throw_15.setMaximumSize(QtCore.QSize(20, 30))
        self.throw_15.setText("")
        self.throw_15.setAlignment(QtCore.Qt.AlignCenter)
        self.throw_15.setObjectName("throw_15")
        self.horizontalLayout_52.addWidget(self.throw_15)
        self.line_44 = QtGui.QFrame(self.horizontalLayoutWidget_85)
        self.line_44.setFrameShape(QtGui.QFrame.VLine)
        self.line_44.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_44.setObjectName("line_44")
        self.horizontalLayout_52.addWidget(self.line_44)
        self.throw_16 = QtGui.QLabel(self.horizontalLayoutWidget_85)
        self.throw_16.setMinimumSize(QtCore.QSize(20, 30))
        self.throw_16.setMaximumSize(QtCore.QSize(20, 30))
        self.throw_16.setText("")
        self.throw_16.setAlignment(QtCore.Qt.AlignCenter)
        self.throw_16.setObjectName("throw_16")
        self.horizontalLayout_52.addWidget(self.throw_16)
        self.horizontalLayout.addWidget(self.frame_8)
        self.line_55 = QtGui.QFrame(self.verticalLayoutWidget)
        self.line_55.setFrameShape(QtGui.QFrame.VLine)
        self.line_55.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_55.setObjectName("line_55")
        self.horizontalLayout.addWidget(self.line_55)
        self.frame_9 = QtGui.QWidget(self.verticalLayoutWidget)
        self.frame_9.setMinimumSize(QtCore.QSize(60, 70))
        self.frame_9.setMaximumSize(QtCore.QSize(60, 70))
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayoutWidget_86 = QtGui.QWidget(self.frame_9)
        self.horizontalLayoutWidget_86.setGeometry(QtCore.QRect(0, 30, 51, 42))
        self.horizontalLayoutWidget_86.setObjectName("horizontalLayoutWidget_86")
        self.horizontalLayout_53 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_86)
        self.horizontalLayout_53.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_53.setObjectName("horizontalLayout_53")
        self.score_9 = QtGui.QLabel(self.horizontalLayoutWidget_86)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(40)
        sizePolicy.setVerticalStretch(40)
        sizePolicy.setHeightForWidth(self.score_9.sizePolicy().hasHeightForWidth())
        self.score_9.setSizePolicy(sizePolicy)
        self.score_9.setMinimumSize(QtCore.QSize(40, 40))
        self.score_9.setText("")
        self.score_9.setAlignment(QtCore.Qt.AlignCenter)
        self.score_9.setObjectName("score_9")
        self.horizontalLayout_53.addWidget(self.score_9)
        self.horizontalLayoutWidget_87 = QtGui.QWidget(self.frame_9)
        self.horizontalLayoutWidget_87.setGeometry(QtCore.QRect(0, 0, 57, 32))
        self.horizontalLayoutWidget_87.setObjectName("horizontalLayoutWidget_87")
        self.horizontalLayout_54 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_87)
        self.horizontalLayout_54.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_54.setObjectName("horizontalLayout_54")
        self.throw_17 = QtGui.QLabel(self.horizontalLayoutWidget_87)
        self.throw_17.setMinimumSize(QtCore.QSize(20, 30))
        self.throw_17.setMaximumSize(QtCore.QSize(20, 30))
        self.throw_17.setText("")
        self.throw_17.setAlignment(QtCore.Qt.AlignCenter)
        self.throw_17.setObjectName("throw_17")
        self.horizontalLayout_54.addWidget(self.throw_17)
        self.line_45 = QtGui.QFrame(self.horizontalLayoutWidget_87)
        self.line_45.setFrameShape(QtGui.QFrame.VLine)
        self.line_45.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_45.setObjectName("line_45")
        self.horizontalLayout_54.addWidget(self.line_45)
        self.throw_18 = QtGui.QLabel(self.horizontalLayoutWidget_87)
        self.throw_18.setMinimumSize(QtCore.QSize(20, 30))
        self.throw_18.setMaximumSize(QtCore.QSize(20, 30))
        self.throw_18.setText("")
        self.throw_18.setAlignment(QtCore.Qt.AlignCenter)
        self.throw_18.setObjectName("throw_18")
        self.horizontalLayout_54.addWidget(self.throw_18)
        self.horizontalLayout.addWidget(self.frame_9)
        self.line_56 = QtGui.QFrame(self.verticalLayoutWidget)
        self.line_56.setFrameShape(QtGui.QFrame.VLine)
        self.line_56.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_56.setObjectName("line_56")
        self.horizontalLayout.addWidget(self.line_56)
        self.frame_10 = QtGui.QWidget(self.verticalLayoutWidget)
        self.frame_10.setMinimumSize(QtCore.QSize(95, 70))
        self.frame_10.setMaximumSize(QtCore.QSize(90, 70))
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayoutWidget_88 = QtGui.QWidget(self.frame_10)
        self.horizontalLayoutWidget_88.setGeometry(QtCore.QRect(0, 30, 91, 42))
        self.horizontalLayoutWidget_88.setObjectName("horizontalLayoutWidget_88")
        self.horizontalLayout_55 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_88)
        self.horizontalLayout_55.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_55.setObjectName("horizontalLayout_55")
        self.score_10 = QtGui.QLabel(self.horizontalLayoutWidget_88)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(40)
        sizePolicy.setVerticalStretch(40)
        sizePolicy.setHeightForWidth(self.score_10.sizePolicy().hasHeightForWidth())
        self.score_10.setSizePolicy(sizePolicy)
        self.score_10.setMinimumSize(QtCore.QSize(40, 40))
        self.score_10.setText("")
        self.score_10.setAlignment(QtCore.Qt.AlignCenter)
        self.score_10.setObjectName("score_10")
        self.horizontalLayout_55.addWidget(self.score_10)
        self.horizontalLayoutWidget_89 = QtGui.QWidget(self.frame_10)
        self.horizontalLayoutWidget_89.setGeometry(QtCore.QRect(0, 0, 92, 32))
        self.horizontalLayoutWidget_89.setObjectName("horizontalLayoutWidget_89")
        self.horizontalLayout_56 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_89)
        self.horizontalLayout_56.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_56.setObjectName("horizontalLayout_56")
        self.throw_19 = QtGui.QLabel(self.horizontalLayoutWidget_89)
        self.throw_19.setMinimumSize(QtCore.QSize(20, 30))
        self.throw_19.setMaximumSize(QtCore.QSize(20, 30))
        self.throw_19.setText("")
        self.throw_19.setAlignment(QtCore.Qt.AlignCenter)
        self.throw_19.setObjectName("throw_19")
        self.horizontalLayout_56.addWidget(self.throw_19)
        self.line_46 = QtGui.QFrame(self.horizontalLayoutWidget_89)
        self.line_46.setFrameShape(QtGui.QFrame.VLine)
        self.line_46.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_46.setObjectName("line_46")
        self.horizontalLayout_56.addWidget(self.line_46)
        self.throw_20 = QtGui.QLabel(self.horizontalLayoutWidget_89)
        self.throw_20.setMinimumSize(QtCore.QSize(20, 30))
        self.throw_20.setMaximumSize(QtCore.QSize(20, 30))
        self.throw_20.setText("")
        self.throw_20.setAlignment(QtCore.Qt.AlignCenter)
        self.throw_20.setObjectName("throw_20")
        self.horizontalLayout_56.addWidget(self.throw_20)
        self.line_47 = QtGui.QFrame(self.horizontalLayoutWidget_89)
        self.line_47.setFrameShape(QtGui.QFrame.VLine)
        self.line_47.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_47.setObjectName("line_47")
        self.horizontalLayout_56.addWidget(self.line_47)
        self.throw_21 = QtGui.QLabel(self.horizontalLayoutWidget_89)
        self.throw_21.setMinimumSize(QtCore.QSize(20, 0))
        self.throw_21.setMaximumSize(QtCore.QSize(20, 16777215))
        self.throw_21.setText("")
        self.throw_21.setAlignment(QtCore.Qt.AlignCenter)
        self.throw_21.setObjectName("throw_21")
        self.horizontalLayout_56.addWidget(self.throw_21)
        self.horizontalLayout.addWidget(self.frame_10)
        self.line_58 = QtGui.QFrame(self.verticalLayoutWidget)
        self.line_58.setFrameShape(QtGui.QFrame.VLine)
        self.line_58.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_58.setObjectName("line_58")
        self.horizontalLayout.addWidget(self.line_58)
        self.cum_score = QtGui.QLabel(self.verticalLayoutWidget)
        self.cum_score.setMinimumSize(QtCore.QSize(40, 0))
        self.cum_score.setMaximumSize(QtCore.QSize(50, 16777215))
        self.cum_score.setAlignment(QtCore.Qt.AlignCenter)
        self.cum_score.setObjectName("cum_score")
        self.horizontalLayout.addWidget(self.cum_score)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line_60 = QtGui.QFrame(self.verticalLayoutWidget)
        self.line_60.setFrameShape(QtGui.QFrame.HLine)
        self.line_60.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_60.setObjectName("line_60")
        self.verticalLayout.addWidget(self.line_60)

        self.retranslateUi(bowler_score)
        QtCore.QMetaObject.connectSlotsByName(bowler_score)

    def retranslateUi(self, bowler_score):
        bowler_score.setWindowTitle(QtGui.QApplication.translate("bowler_score", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.player_name.setText(QtGui.QApplication.translate("bowler_score", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.cum_score.setText(QtGui.QApplication.translate("bowler_score", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))

